# Configuración básica de Jekyll
title: AutosplitterCore
description: AutoSplitterCore Addons for HitCounterManager
theme: minima

# Metaetiquetas personalizadas
google_site_verification: LKMcIo0p7OTWvmskwPXyNjXRtcItFtbkdA1okHgM7MM