//MIT License

//Copyright (c) 2022-2025 Ezequiel Medina

//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:

//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.

//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.

using System;
using System.Collections.Generic;

namespace AutoSplitterCore
{
    public class DefinitionsElden
    {
        #region Boss.Elden
        [Serializable]
        public class BossER
        {
            public string Title;
            public uint Id;
            public bool IsSplited = false;
            public string Mode;

        }

        public BossER StringToEnumBoss(string boss)
        {
            var bossMapping = new Dictionary<string, (string Title, uint Id)>
            {
                { "Godrick the Grafted - Stormveil Castle", ("Godrick the Grafted - Stormveil Castle", 10000800) },
                { "Margit, the Fell Omen - Stormveil Castle", ("Margit, the Fell Omen - Stormveil Castle", 10000850) },
                { "Grafted Scion - Chapel of Anticipation", ("Grafted Scion - Chapel of Anticipation", 10010800) },
                { "Morgott, the Omen King - Leyndell", ("Morgott, the Omen King - Leyndell", 11000800) },
                { "Godfrey, First Elden Lord - Leyndell", ("Godfrey, First Elden Lord - Leyndell", 11000850) },
                { "Hoarah Loux - Leyndell", ("Hoarah Loux - Leyndell", 11050800) },
                { "Sir Gideon Ofnir, the All-Knowing - Leyndell", ("Sir Gideon Ofnir, the All-Knowing - Leyndell", 11050850) },
                { "Dragonkin Soldier of Nokstella - Ainsel River", ("Dragonkin Soldier of Nokstella - Ainsel River", 12010800) },
                { "Dragonkin Soldier - Lake of Rot", ("Dragonkin Soldier - Lake of Rot", 12010850) },
                { "Valiant Gargoyles - Siofra River", ("Valiant Gargoyles - Siofra River", 12020800) },
                { "Dragonkin Soldier - Siofra River", ("Dragonkin Soldier - Siofra River", 12020830) },
                { "Mimic Tear - Siofra River", ("Mimic Tear - Siofra River", 12020850) },
                { "Crucible Knight Sirulia - Deeproot Depths", ("Crucible Knight Sirulia - Deeproot Depths", 12030390) },
                { "Fia's Champion - Deeproot Depths", ("Fia's Champion - Deeproot Depths", 12030800) },
                { "Lichdragon Fortissax - Deeproot Depths", ("Lichdragon Fortissax - Deeproot Depths", 12030850) },
                { "Astel, Naturalborn of the Void - Lake of Rot", ("Astel, Naturalborn of the Void - Lake of Rot", 12040800) },
                { "Mohg, Lord of Blood - Mohgwyn Palace", ("Mohg, Lord of Blood - Mohgwyn Palace", 12050800) },
                { "Ancestor Spirit - Siofra River", ("Ancestor Spirit - Siofra River", 12080800) },
                { "Regal Ancestor Spirit - Nokron, Eternal City", ("Regal Ancestor Spirit - Nokron, Eternal City", 12090800) },
                { "Maliketh, The Black Blade - Crumbling Farum Azula", ("Maliketh, The Black Blade - Crumbling Farum Azula", 13000800) },
                { "Dragonlord Placidusax - Crumbling Farum Azula", ("Dragonlord Placidusax - Crumbling Farum Azula", 13000830) },
                { "Godskin Duo - Crumbling Farum Azula", ("Godskin Duo - Crumbling Farum Azula", 13000850) },
                { "Rennala, Queen of the Full Moon - Academy of Raya Lucaria", ("Rennala, Queen of the Full Moon - Academy of Raya Lucaria", 14000800) },
                { "Red Wolf of Radagon - Academy of Raya Lucaria", ("Red Wolf of Radagon - Academy of Raya Lucaria", 14000850) },
                { "Malenia, Blade of Miquella - Miquella's Haligtree", ("Malenia, Blade of Miquella - Miquella's Haligtree", 15000800) },
                { "Loretta, Knight of the Haligtree - Miquella's Haligtree", ("Loretta, Knight of the Haligtree - Miquella's Haligtree", 15000850) },
                { "Rykard, Lord of Blasphemy - Volcano Manor", ("Rykard, Lord of Blasphemy - Volcano Manor", 16000800) },
                { "Godskin Noble - Volcano Manor", ("Godskin Noble - Volcano Manor", 16000850) },
                { "Abductor Virgins - Volcano Manor", ("Abductor Virgins - Volcano Manor", 16000860) },
                { "Ulcerated Tree Spirit - Stranded Graveyard", ("Ulcerated Tree Spirit - Stranded Graveyard", 18000800) },
                { "Soldier of Godrick - Stranded Graveyard", ("Soldier of Godrick - Stranded Graveyard", 18000850) },
                { "Elden Beast - Elden Throne", ("Elden Beast - Elden Throne", 19000800) },
                { "Mohg, The Omen - Subterranean Shunning-Grounds (Leyndell)", ("Mohg, The Omen - Subterranean Shunning-Grounds (Leyndell)", 35000800) },
                { "Esgar, Priest of Blood - Subterranean Shunning-Grounds (Leyndell)", ("Esgar, Priest of Blood - Subterranean Shunning-Grounds (Leyndell)", 35000850) },
                { "Magma Wyrm Makar - Ruin-Strewn Precipice (Liurnia)", ("Magma Wyrm Makar - Ruin-Strewn Precipice (Liurnia)", 39200800) },
                { "Cemetery Shade - Tombsward Catacombs (Limgrave)", ("Cemetery Shade - Tombsward Catacombs (Limgrave)", 30000800) },
                { "Erdtree Burial Watchdog - Impaler's Catacombs (Weeping Penisula)", ("Erdtree Burial Watchdog - Impaler's Catacombs (Weeping Penisula)", 30010800) },
                { "Erdtree Burial Watchdog - Stormfoot Catacombs (Limgrave)", ("Erdtree Burial Watchdog - Stormfoot Catacombs (Limgrave)", 30020800) },
                { "Black Knife Assassin - Deathtouched Catacombs (Limgrave)", ("Black Knife Assassin - Deathtouched Catacombs (Limgrave)", 30110800) },
                { "Grave Warden Duelist - Murkwater Catacombs (Limgrave)", ("Grave Warden Duelist - Murkwater Catacombs (Limgrave)", 30040800) },
                { "Cemetery Shade - Black Knife Catacombs (Liurnia)", ("Cemetery Shade - Black Knife Catacombs (Liurnia)", 30050800) },
                { "Black Knife Assassin - Black Knife Catacombs (Liurnia)", ("Black Knife Assassin - Black Knife Catacombs (Liurnia)", 30050850) },
                { "Spirit-Caller Snail - Road's End Catacombs (Liurnia)", ("Spirit-Caller Snail - Road's End Catacombs (Liurnia)", 30030800) },
                { "Erdtree Burial Watchdog - Cliffbottom Catacombs (Liurnia)", ("Erdtree Burial Watchdog - Cliffbottom Catacombs (Liurnia)", 30060800) },
                { "Ancient Hero of Zamor - Sainted Hero's Grave (Altus Plateau)", ("Ancient Hero of Zamor - Sainted Hero's Grave (Altus Plateau)", 30080800) },
                { "Red Wolf of the Champion - Gelmir Hero's Grave (Mt. Gelmir)", ("Red Wolf of the Champion - Gelmir Hero's Grave (Mt. Gelmir)", 30090800) },
                { "Crucible Knight Ordovis - Auriza Hero's Grave (Altus Plateau)", ("Crucible Knight Ordovis - Auriza Hero's Grave (Altus Plateau)", 30100800) },
                { "Crucible Knight (Tree Spear) - Auriza Hero's Grave (Altus Plateau)", ("Crucible Knight (Tree Spear) - Auriza Hero's Grave (Altus Plateau)", 30100800) },
                { "Misbegotten Warrior - Unsightly Catacombs (Mt. Gelmir)", ("Misbegotten Warrior - Unsightly Catacombs (Mt. Gelmir)", 30120800) },
                { "Perfumer Tricia - Unsightly Catacombs (Mt. Gelmir)", ("Perfumer Tricia - Unsightly Catacombs (Mt. Gelmir)", 30120800) },
                { "Erdtree Burial Watchdog - Wyndham Catacombs (Altus Plateau)", ("Erdtree Burial Watchdog - Wyndham Catacombs (Altus Plateau)", 30070800) },
                { "Grave Warden Duelist - Auriza Side Tomb (Altus Plateau)", ("Grave Warden Duelist - Auriza Side Tomb (Altus Plateau)", 30130800) },
                { "Erdtree Burial Watchdog - Minor Erdtree Catacombs (Caelid)", ("Erdtree Burial Watchdog - Minor Erdtree Catacombs (Caelid)", 30140800) },
                { "Cemetery Shade - Caelid Catacombs (Caelid)", ("Cemetery Shade - Caelid Catacombs (Caelid)", 30150800) },
                { "Putrid Tree Spirit - War-Dead Catacombs (Caelid)", ("Putrid Tree Spirit - War-Dead Catacombs (Caelid)", 30160800) },
                { "Ancient Hero of Zamor - Giant-Conquering Hero's Grave (Mountaintops)", ("Ancient Hero of Zamor - Giant-Conquering Hero's Grave (Mountaintops)", 30170800) },
                { "Ulcerated Tree Sprit - Giants' Mountaintop Catacombs (Mountaintops)", ("Ulcerated Tree Sprit - Giants' Mountaintop Catacombs (Mountaintops)", 30180800) },
                { "Putrid Grave Warden Duelist - Consecrated Snowfield Catacombs (Snowfield)", ("Putrid Grave Warden Duelist - Consecrated Snowfield Catacombs (Snowfield)", 30190800) },
                { "Stray Mimic Tear - Hidden Path to the Haligtree", ("Stray Mimic Tear - Hidden Path to the Haligtree", 30202800) },
                { "Patches - Murkwater Cave (Limgrave)", ("Patches - Murkwater Cave (Limgrave)", 31000800) },
                { "Runebear - Earthbore Cave (Weeping Penisula)", ("Runebear - Earthbore Cave (Weeping Penisula)", 31010800) },
                { "Miranda the Blighted Bloom - Tombsward Cave (Limgrave)", ("Miranda the Blighted Bloom - Tombsward Cave (Limgrave)", 31020800) },
                { "Beastman of Farum Azula - Groveside Cave (Limgrave)", ("Beastman of Farum Azula - Groveside Cave (Limgrave)", 31030800) },
                { "Demi-Human Chief - Coastal Cave (Limgrave)", ("Demi-Human Chief - Coastal Cave (Limgrave)", 31150800) },
                { "Guardian Golem - Highroad Cave (Limgrave)", ("Guardian Golem - Highroad Cave (Limgrave)", 31170800) },
                { "Cleanrot Knight - Stillwater Cave (Liurnia)", ("Cleanrot Knight - Stillwater Cave (Liurnia)", 31040800) },
                { "Bloodhound Knight - Lakeside Crystal Cave (Liurnia)", ("Bloodhound Knight - Lakeside Crystal Cave (Liurnia)", 31050800) },
                { "Crystalians - Academy Crystal Cave (Liurnia)", ("Crystalians - Academy Crystal Cave (Liurnia)", 31060800) },
                { "Kindred of Rot - Seethewater Cave (Mt. Gelmir)", ("Kindred of Rot - Seethewater Cave (Mt. Gelmir)", 31070800) },
                { "Demi-Human Queen Margot - Volcano Cave (Mt. Gelmir)", ("Demi-Human Queen Margot - Volcano Cave (Mt. Gelmir)", 31090800) },
                { "Miranda the Blighted Bloom - Perfumer's Grotto (Altus Plateau)", ("Miranda the Blighted Bloom - Perfumer's Grotto (Altus Plateau)", 31180800) },
                { "Black Knife Assassin - Sage's Cave (Altus Plateau)", ("Black Knife Assassin - Sage's Cave (Altus Plateau)", 31190800) },
                { "Necromancer Garris - Sage's Cave (Altus Plateau)", ("Necromancer Garris - Sage's Cave (Altus Plateau)", 31190850) },
                { "Frenzied Duelist - Gaol Cave (Caelid)", ("Frenzied Duelist - Gaol Cave (Caelid)", 31210800) },
                { "Beastman of Farum Azula - Dragonbarrow Cave (Dragonbarrow)", ("Beastman of Farum Azula - Dragonbarrow Cave (Dragonbarrow)", 31100800) },
                { "Cleanrot Knight - Abandoned Cave (Caelid)", ("Cleanrot Knight - Abandoned Cave (Caelid)", 31200800) },
                { "Putrid Crystalians - Sellia Hideaway (Caelid)", ("Putrid Crystalians - Sellia Hideaway (Caelid)", 31110800) },
                { "Misbegotten Crusader - Cave of the Forlorn (Mountaintops)", ("Misbegotten Crusader - Cave of the Forlorn (Mountaintops)", 31120800) },
                { "Spirit-Caller Snail - Spiritcaller's Cave (Mountaintops)", ("Spirit-Caller Snail - Spiritcaller's Cave (Mountaintops)", 31220800) },
                { "Scaly Misbegotten - Morne Tunnel (Weeping Penisula)", ("Scaly Misbegotten - Morne Tunnel (Weeping Penisula)", 32000800) },
                { "Stonedigger Troll - Limgrave Tunnels (Limgrave)", ("Stonedigger Troll - Limgrave Tunnels (Limgrave)", 32010800) },
                { "Crystalian (Ringblade) - Raya Lucaria Crystal Tunnel (Liurnia)", ("Crystalian (Ringblade) - Raya Lucaria Crystal Tunnel (Liurnia)", 32020800) },
                { "Stonedigger Troll - Old Altus Tunnel (Altus Plateau)", ("Stonedigger Troll - Old Altus Tunnel (Altus Plateau)", 32040800) },
                { "Onyx Lord - Divine Tower of West Altus (Altus Plateau)", ("Onyx Lord - Divine Tower of West Altus (Altus Plateau)", 34120800) },
                { "Crystalian (Ringblade) - Altus Tunnel (Altus Plateau)", ("Crystalian (Ringblade) - Altus Tunnel (Altus Plateau)", 32050800) },
                { "Crystalian (Spear) - Altus Tunnel (Altus Plateau)", ("Crystalian (Spear) - Altus Tunnel (Altus Plateau)", 32050800) },
                { "Magma Wyrm - Gael Tunnel (Caelid)", ("Magma Wyrm - Gael Tunnel (Caelid)", 32070800) },
                { "Fallingstar Beast - Sellia Crystal Tunnel (Caelid)", ("Fallingstar Beast - Sellia Crystal Tunnel (Caelid)", 32080800) },
                { "Astel, Stars of Darkness - Yelough Anix Tunnel (Snowfield)", ("Astel, Stars of Darkness - Yelough Anix Tunnel (Snowfield)", 32110800) },
                { "Godskin Apostle - Divine Tower of Caelid (Caelid)", ("Godskin Apostle - Divine Tower of Caelid (Caelid)", 34130800) },
                { "Fell Twins - Divine Tower of East Altus (Capital Outskirts)", ("Fell Twins - Divine Tower of East Altus (Capital Outskirts)", 34140850) },
                { "Mad Pumpkin Head - Waypoint Ruins (Limgrave)", ("Mad Pumpkin Head - Waypoint Ruins (Limgrave)", 1044360800) },
                { "Night's Cavalry - Agheel Lake North (Limgrave)", ("Night's Cavalry - Agheel Lake North (Limgrave)", 1043370800) },
                { "Deathbird - Stormgate (Limgrave)", ("Deathbird - Stormgate (Limgrave)", 1042380800) },
                { "Ball-Bearing Hunter - Warmaster's Shack (Limgrave)", ("Ball-Bearing Hunter - Warmaster's Shack (Limgrave)", 1042380850) },
                { "Ancient Hero of Zamor - Weeping Evergaol (Weeping Penisula)", ("Ancient Hero of Zamor - Weeping Evergaol (Weeping Penisula)", 1042330800) },
                { "Bloodhound Knight Darriwill - Forlorn Hound Evergaol (Limgrave)", ("Bloodhound Knight Darriwill - Forlorn Hound Evergaol (Limgrave)", 1044350800) },
                { "Crucible Knight - Stormhill Evergaol (Limgrave)", ("Crucible Knight - Stormhill Evergaol (Limgrave)", 1042370800) },
                { "Erdtree Avatar - Minor Erdtree (Weeping Penisula)", ("Erdtree Avatar - Minor Erdtree (Weeping Penisula)", 1043330800) },
                { "Night's Cavalry - Castle Morne Approach (Weeping Penisula)", ("Night's Cavalry - Castle Morne Approach (Weeping Penisula)", 1044320850) },
                { "Deathbird - Castle Morne Approach (Weeping Penisula)", ("Deathbird - Castle Morne Approach (Weeping Penisula)", 1044320800) },
                { "Leonine Misbegotten - Castle Morne (Weeping Penisula)", ("Leonine Misbegotten - Castle Morne (Weeping Penisula)", 1043300800) },
                { "Tree Sentinel - Church of Elleh (Limgrave)", ("Tree Sentinel - Church of Elleh (Limgrave)", 1042360800) },
                { "Flying Dragon Agheel - Dragon-Burnt Ruins (Limgrave)", ("Flying Dragon Agheel - Dragon-Burnt Ruins (Limgrave)", 1043360800) },
                { "Tibia Mariner - Summonwater Village (Limgrave)", ("Tibia Mariner - Summonwater Village (Limgrave)", 1045390800) },
                { "Royal Revenant - Kingsrealm Ruins (Liurnia)", ("Royal Revenant - Kingsrealm Ruins (Liurnia)", 1034480800) },
                { "Adan, Thief of Fire - Malefactor's Evergaol (Liurnia)", ("Adan, Thief of Fire - Malefactor's Evergaol (Liurnia)", 1038410800) },
                { "Bols, Carian Knight - Cuckoo's Evergaol (Liurnia)", ("Bols, Carian Knight - Cuckoo's Evergaol (Liurnia)", 1033450800) },
                { "Onyx Lord - Royal Grave Evergaol (Liurnia)", ("Onyx Lord - Royal Grave Evergaol (Liurnia)", 1036500800) },
                { "Alecto, Black Knife Ringleader - Moonlight Altar (Liurnia)", ("Alecto, Black Knife Ringleader - Moonlight Altar (Liurnia)", 1033420800) },
                { "Erdtree Avatar - Revenger's Shack (Liurnia)", ("Erdtree Avatar - Revenger's Shack (Liurnia)", 1033430800) },
                { "Erdtree Avatar - Minor Erdtree (Liurnia)", ("Erdtree Avatar - Minor Erdtree (Liurnia)", 1038480800) },
                { "Royal Knight Loretta - Carian Manor (Liurnia)", ("Royal Knight Loretta - Carian Manor (Liurnia)", 1035500800) },
                { "Ball-Bearing Hunter - Church of Vows (Liurnia)", ("Ball-Bearing Hunter - Church of Vows (Liurnia)", 1037460800) },
                { "Night's Cavalry - Liurnia Highway Far North (Liurnia)", ("Night's Cavalry - Liurnia Highway Far North (Liurnia)", 1039430800) },
                { "Night's Cavalry - East Raya Lucaria Gate (Liurnia)", ("Night's Cavalry - East Raya Lucaria Gate (Liurnia)", 1036480800) },
                { "Deathbird - Laskyar Ruins (Liurnia)", ("Deathbird - Laskyar Ruins (Liurnia)", 1037420800) },
                { "Death Rite Bird - Gate Town Northwest (Liurnia)", ("Death Rite Bird - Gate Town Northwest (Liurnia)", 1036450800) },
                { "Glintstone Dragon Smarag - Meeting Place (Liurnia)", ("Glintstone Dragon Smarag - Meeting Place (Liurnia)", 1034450800) },
                { "Glintstone Dragon Adula - Ranni's Rise (Liurnia)", ("Glintstone Dragon Adula - Ranni's Rise (Liurnia)", 1034500800) },
                { "Glintstone Dragon Adula - Moonfolk Ruins (Liurnia)", ("Glintstone Dragon Adula - Moonfolk Ruins (Liurnia)", 1034420800) },
                { "Omenkiller - Village of the Albinaurics (Liurnia)", ("Omenkiller - Village of the Albinaurics (Liurnia)", 1035420800) },
                { "Tibia Mariner - Jarburg (Liurnia)", ("Tibia Mariner - Jarburg (Liurnia)", 1039440800) },
                { "Ancient Dragon Lansseax - Abandoned Coffin (Altus Plateau)", ("Ancient Dragon Lansseax - Abandoned Coffin (Altus Plateau)", 1037510800) },
                { "Ancient Dragon Lansseax - Rampartside Path (Altus Plateau)", ("Ancient Dragon Lansseax - Rampartside Path (Altus Plateau)", 1041520800) },
                { "Demi-Human Queen - Lux Ruins (Altus Plateau)", ("Demi-Human Queen - Lux Ruins (Altus Plateau)", 1038510800) },
                { "Fallingstar Beast - South of Tree Sentinel Duo (Altus Plateau)", ("Fallingstar Beast - South of Tree Sentinel Duo (Altus Plateau)", 1041500800) },
                { "Sanguine Noble - Writheblood Ruins (Altus Plateau)", ("Sanguine Noble - Writheblood Ruins (Altus Plateau)", 1040530800) },
                { "Tree Sentinel - Tree Sentinel Duo (Altus Plateau)", ("Tree Sentinel - Tree Sentinel Duo (Altus Plateau)", 1041510800) },
                { "Godskin Apostle - Windmill Heights (Altus Plateau)", ("Godskin Apostle - Windmill Heights (Altus Plateau)", 1042550800) },
                { "Black Knife Assassin - Sainted Hero's Grave Entrance (Altus Plateau)", ("Black Knife Assassin - Sainted Hero's Grave Entrance (Altus Plateau)", 1040520800) },
                { "Draconic Tree Sentinel - Capital Rampart (Capital Outskirts)", ("Draconic Tree Sentinel - Capital Rampart (Capital Outskirts)", 1045520800) },
                { "Godefroy the Grafted - Golden Lineage Evergaol (Altus Plateau)", ("Godefroy the Grafted - Golden Lineage Evergaol (Altus Plateau)", 1039500800) },
                { "Wormface - Woodfolk Ruins (Altus Plateau)", ("Wormface - Woodfolk Ruins (Altus Plateau)", 1041530800) },
                { "Ball-Bearing Hunter - Hermit Merchant's Shack (Capital Outskirts)", ("Ball-Bearing Hunter - Hermit Merchant's Shack (Capital Outskirts)", 1043530800) },
                { "Demi-Human Queen - Primeval Sorcerer Azur (Mt. Gelmir)", ("Demi-Human Queen - Primeval Sorcerer Azur (Mt. Gelmir)", 1037530800) },
                { "Magma Wyrm - Seethewater Terminus (Mt. Gelmir)", ("Magma Wyrm - Seethewater Terminus (Mt. Gelmir)", 1035530800) },
                { "Full-Grown Fallingstar Beast - Crater (Mt. Gelmir)", ("Full-Grown Fallingstar Beast - Crater (Mt. Gelmir)", 1036540800) },
                { "Elemer of the Briar - Shaded Castle (Altus Plateau)", ("Elemer of the Briar - Shaded Castle (Altus Plateau)", 1039540800) },
                { "Ulcerated Tree Spirit - Minor Erdtree (Mt. Gelmir)", ("Ulcerated Tree Spirit - Minor Erdtree (Mt. Gelmir)", 1037540810) },
                { "Tibia Mariner - Wyndham Ruins (Altus Plateau)", ("Tibia Mariner - Wyndham Ruins (Altus Plateau)", 1038520800) },
                { "Putrid Avatar - Minor Erdtree (Caelid)", ("Putrid Avatar - Minor Erdtree (Caelid)", 1047400800) },
                { "Decaying Ekzykes - Caelid Highway South (Caelid)", ("Decaying Ekzykes - Caelid Highway South (Caelid)", 1048370800) },
                { "Night's Cavalry - Southern Aeonia Swamp Bank (Caelid)", ("Night's Cavalry - Southern Aeonia Swamp Bank (Caelid)", 1049370800) },
                { "Death Rite Bird - Southern Aeonia Swamp Bank (Caelid)", ("Death Rite Bird - Southern Aeonia Swamp Bank (Caelid)", 1049370850) },
                { "Commander O'Neil - East Aeonia Swamp (Caelid)", ("Commander O'Neil - East Aeonia Swamp (Caelid)", 1049380800) },
                { "Crucible Knight - Redmane Castle (Caelid)", ("Crucible Knight - Redmane Castle (Caelid)", 1051360800) },
                { "Starscourge Radahn - Battlefield (Caelid)", ("Starscourge Radahn - Battlefield (Caelid)", 1252380800) },
                { "Nox Priest - West Sellia (Caelid)", ("Nox Priest - West Sellia (Caelid)", 1049390800) },
                { "Bell-Bearing Hunter - Isolated Merchant's Shack (Dragonbarrow)", ("Bell-Bearing Hunter - Isolated Merchant's Shack (Dragonbarrow)", 1048410800) },
                { "Battlemage Hugues - Sellia Crystal Tunnel Entrance (Caelid)", ("Battlemage Hugues - Sellia Crystal Tunnel Entrance (Caelid)", 1049390850) },
                { "Putrid Avatar - Dragonbarrow Fork (Caelid)", ("Putrid Avatar - Dragonbarrow Fork (Caelid)", 1051400800) },
                { "Flying Dragon Greyll - Dragonbarrow (Caelid)", ("Flying Dragon Greyll - Dragonbarrow (Caelid)", 1052410800) },
                { "Night's Cavalry - Dragonbarrow (Caelid)", ("Night's Cavalry - Dragonbarrow (Caelid)", 1052410850) },
                { "Black Blade Kindred - Bestial Sanctum (Caelid)", ("Black Blade Kindred - Bestial Sanctum (Caelid)", 1051430800) },
                { "Night's Cavalry - Forbidden Lands (Mountaintops)", ("Night's Cavalry - Forbidden Lands (Mountaintops)", 1048510800) },
                { "Black Blade Kindred - Before Grand Lift of Rold (Mountaintops)", ("Black Blade Kindred - Before Grand Lift of Rold (Mountaintops)", 1049520800) },
                { "Borealis the Freezing Fog - Freezing Fields (Mountaintops)", ("Borealis the Freezing Fog - Freezing Fields (Mountaintops)", 1254560800) },
                { "Roundtable Knight Vyke - Lord Contender's Evergaol (Mountaintops)", ("Roundtable Knight Vyke - Lord Contender's Evergaol (Mountaintops)", 1053560800) },
                { "Fire Giant - Giant's Forge (Mountaintops)", ("Fire Giant - Giant's Forge (Mountaintops)", 1052520800) },
                { "Erdtree Avatar - Minor Erdtree (Mountaintops)", ("Erdtree Avatar - Minor Erdtree (Mountaintops)", 1052560800) },
                { "Death Rite Bird - West of Castle So (Mountaintops)", ("Death Rite Bird - West of Castle So (Mountaintops)", 1050570800) },
                { "Putrid Avatar - Minor Erdtree (Snowfield)", ("Putrid Avatar - Minor Erdtree (Snowfield)", 1050570850) },
                { "Commander Niall - Castle Soul (Mountaintops)", ("Commander Niall - Castle Soul (Mountaintops)", 1051570800) },
                { "Great Wyrm Theodorix - Albinauric Rise (Mountaintops)", ("Great Wyrm Theodorix - Albinauric Rise (Mountaintops)", 1050560800) },
                { "Night's Cavalry - Sourthwest (Mountaintops)", ("Night's Cavalry - Sourthwest (Mountaintops)", 1248550800) },
                { "Death Rite Bird - Ordina, Liturgical Town (Snowfield)", ("Death Rite Bird - Ordina, Liturgical Town (Snowfield)", 1048570800) },
                { "Deathbird - Minor Erdtree (Capital Outskirts)", ("Deathbird - Minor Erdtree (Capital Outskirts)", 1044530800) },
                #region DLC Boss
                { "Ghostflame Dragon - Gravesite Plain (Northwest)", ("Ghostflame Dragon - Gravesite Plain (Northwest)", 2045440800)},
                { "Blackgaol Knight - Western Nameless Mausoleum", ( "Blackgaol Knight - Western Nameless Mausoleum", 2046410800)},
                { "Chief Bloodfiend - Rivermouth Cave", ("Chief Bloodfiend - Rivermouth Cave", 43000800)},
                { "Lamenter - Lamenter's Gaol", ("Lamenter - Lamenter's Gaol", 41020800)},
                { "Demi-Human Swordmaster Onze - Belurat Gaol", ("Demi-Human Swordmaster Onze - Belurat Gaol", 41000800)},
                { "Divine Beast Dancing Lion - Belurat, Tower Settlement", ("Divine Beast Dancing Lion - Belurat, Tower Settlement", 20000800)},
                { "Rellana, Twin Moon Knight - Castle Ensis", ("Rellana, Twin Moon Knight - Castle Ensis", 2048440800)},
                { "Ghostflame Dragon", ("Ghostflame Dragon", 2049430800)},
                { "Ralva the Great Red Bear", ("Ralva the Great Red Bear", 2049450800)},
                { "Rugalea the Great Red Bear - Rauh Base (Northwest)", ("Rugalea the Great Red Bear - Rauh Base (Northwest)", 2044470800)},
                { "Dryleaf Dane - Moorth Ruins", ("Dryleaf Dane - Moorth Ruins", 2049440800)},
                { "Black Knight Edredd - Fort of Reprimand", ("Black Knight Edredd - Fort of Reprimand", 2049430850)},
                { "Black Knight Garrew - Fog Rift Fort", ("Black Knight Garrew - Fog Rift Fort", 2047450800)},
                { "Red Bear - Northern Nameless Mausoleum", ("Red Bear - Northern Nameless Mausoleum", 2046450800)},
                { "Rakshasa - Eastern Nameless Mausoleum", ("Rakshasa - Eastern Nameless Mausoleum", 2051440800)},
                { "Metyr, Mother of Fingers - Cathedral of Manus Metyr", ("Metyr, Mother of Fingers - Cathedral of Manus Metyr", 25000800)},
                { "Count Ymir, Mother of Fingers - Cathedral of Manus Metyr", ("Count Ymir, Mother of Fingers - Cathedral of Manus Metyr", 2051450800)},
                { "Death Knight - Fog Rift Catacombs", ("Death Knight - Fog Rift Catacombs", 40000800)},
                { "Death Knight - Scorpion River Catacombs", ("Death Knight - Scorpion River Catacombs", 40010800)},
                { "Curseblade Labirith - Bonny Gaol", ("Curseblade Labirith - Bonny Gaol", 41010800)},
                { "Golden Hippopotamus - Main Gate Plaza", ("Golden Hippopotamus - Main Gate Plaza", 21000850)},
                { "Base Serpent Messmer - Messmer's Dark Chamber", ("Base Serpent Messmer - Messmer's Dark Chamber", 21010800)},
                { "Divine Beast Dancing Lion - Ancient Ruins of Rauh", ("Divine Beast Dancing Lion - Ancient Ruins of Rauh", 2046460800)},
                { "Romina, Saint of the Bud - Church of the Bud", ("Romina, Saint of the Bud - Church of the Bud", 2044450800)},
                { "Ghostflame Dragon - Cerulean Coast", ("Ghostflame Dragon - Cerulean Coast", 2048380850)},
                { "Dancer of Ranah - Southern Nameless Mausoleum", ("Dancer of Ranah - Southern Nameless Mausoleum", 2046380800)},
                { "Putrescent Knight - Stone Coffin Fissure", ("Putrescent Knight - Stone Coffin Fissure", 22000800)},
                { "Death Rite Bird - Charo's Hidden Grave", ("Death Rite Bird - Charo's Hidden Grave", 2047390800)},
                { "Demi-Human Queen Marigga - Charo's Hidden Grave (West)", ("Demi-Human Queen Marigga - Charo's Hidden Grave (West)", 2046400800)},
                { "Jagged Peak Drake - Foot of the Jagged Peak", ("Jagged Peak Drake - Foot of the Jagged Peak", 2049410800)},
                { "Jagged Peak Drake - Jagged Peak Mountainside", ("Jagged Peak Drake - Jagged Peak Mountainside", 2052400800)},
                { "Ancient Dragon-Man - Dragon's Pit", ("Ancient Dragon-Man - Dragon's Pit", 43010800)},
                { "Ancient Dragon Senessax - Jagged Peak Mountainside", ("Ancient Dragon Senessax - Jagged Peak Mountainside", 2054390850)},
                { "Bayle the Dread - Jagged Peak Summit", ("Bayle the Dread - Jagged Peak Summit", 2054390800)},
                { "Tree Sentinel - Hinterland", ("Tree Sentinel - Hinterland", 2050470800)},
                { "Tree Sentinel - Hinterland Bridge", ("Tree Sentinel - Hinterland Bridge", 2050480860)},
                { "Fallingstar Beast - Fingerstone Hill", ("Fallingstar Beast - Fingerstone Hill", 2052480800)},
                { "Commander Gaius - Scaduview", ("Commander Gaius - Scaduview", 2049480800)},
                { "Scadutree Avatar - Scadutree Base", ("Scadutree Avatar - Scadutree Base", 2050480800)},
                { "Jori, Elder Inquisitor - Darklight Catacombs", ("Jori, Elder Inquisitor - Darklight Catacombs", 2052430800)},
                { "Midra, Lord of Frenzied Flame - Midra's Manse", ("Midra, Lord of Frenzied Flame - Midra's Manse", 28000800)},
                { "Radahn, Consort of Miquella - Enir-Ilim", ("Radahn, Consort of Miquella - Enir-Ilim", 20010800)}
                #endregion
            };

            if (bossMapping.TryGetValue(boss, out var bossInfo))
            {
                return new BossER { Title = bossInfo.Title, Id = bossInfo.Id };
            }
            else
            {
                throw new ArgumentException($"Invalid boss string: {boss}");
            }
        }
        #endregion
        #region Grace.Elden
        [Serializable]
        public class GraceER
        {
            public string Title;
            public uint Id;
            public bool IsSplited = false;
            public string Mode;
        }

        public GraceER StringToGraceEnum(string grace)
        {
            var graceMapping = new Dictionary<string, (string Title, uint Id)>
            {
                { "Raya Lucaria Grand Library", ("Raya Lucaria Grand Library", 71400)},
                { "Debate Parlor", ("Debate Parlor", 71401)},
                { "Church of the Cuckoo", ("Church of the Cuckoo", 71402)},
                { "Schoolhouse Classroom", ("Schoolhouse Classroom", 71403)},
                { "Dragonkin Soldier of Nokstella", ("Dragonkin Soldier of Nokstella", 71210)},
                { "Ainsel River Well Depths", ("Ainsel River Well Depths", 71211)},
                { "Ainsel River Sluice Gate", ("Ainsel River Sluice Gate", 71212)},
                { "Ainsel River Downstream", ("Ainsel River Downstream", 71213)},
                { "Astel, Naturalborn of the Void", ("Astel, Naturalborn of the Void", 71240)},
                { "Ainsel River Main", ("Ainsel River Main", 71214)},
                { "Nokstella, Eternal City", ("Nokstella, Eternal City", 71215)},
                { "Nokstella Waterfall Basin", ("Nokstella Waterfall Basin", 71219)},
                { "Sainted Hero's Grave", ("Sainted Hero's Grave", 73008)},
                { "Unsightly Catacombs", ("Unsightly Catacombs", 73012)},
                { "Perfumer's Grotto", ("Perfumer's Grotto", 73118)},
                { "Sage's Cave", ("Sage's Cave", 73119)},
                { "Old Altus Tunnel", ("Old Altus Tunnel", 73204)},
                { "Altus Tunnel", ("Altus Tunnel", 73205)},
                { "Abandoned Coffin", ("Abandoned Coffin", 76300)},
                { "Altus Plateau", ("Altus Plateau", 76301)},
                { "Erdtree-Gazing Hill", ("Erdtree-Gazing Hill", 76302)},
                { "Altus Highway Junction", ("Altus Highway Junction", 76303)},
                { "Forest-Spanning Greatbridge", ("Forest-Spanning Greatbridge", 76304)},
                { "Rampartside Path", ("Rampartside Path", 76305)},
                { "Bower of Bounty", ("Bower of Bounty", 76306)},
                { "Road of Iniquity Side Path", ("Road of Iniquity Side Path", 76307)},
                { "Windmill Village", ("Windmill Village", 76308)},
                { "Windmill Heights", ("Windmill Heights", 76313)},
                { "Shaded Castle Ramparts", ("Shaded Castle Ramparts", 76320)},
                { "Shaded Castle Inner Gate", ("Shaded Castle Inner Gate", 76321)},
                { "Castellan's Hall", ("Castellan's Hall", 76322)},
                { "East Raya Lucaria Gate", ("East Raya Lucaria Gate", 76207)},
                { "Bellum Church", ("Bellum Church", 76208)},
                { "Frenzied Flame Village Outskirts", ("Frenzied Flame Village Outskirts", 76239)},
                { "Church of Inhibition", ("Church of Inhibition", 76240)},
                { "Minor Erdtree Catacombs", ("Minor Erdtree Catacombs", 73014)},
                { "Caelid Catacombs", ("Caelid Catacombs", 73015)},
                { "War-Dead Catacombs", ("War-Dead Catacombs", 73016)},
                { "Abandoned Cave", ("Abandoned Cave", 73120)},
                { "Gaol Cave", ("Gaol Cave", 73121)},
                { "Gael Tunnel", ("Gael Tunnel", 73207)},
                { "Rear Gael Tunnel Entrance", ("Rear Gael Tunnel Entrance", 73207)},
                { "Sellia Crystal Tunnel", ("Sellia Crystal Tunnel", 73208)},
                { "Smoldering Church", ("Smoldering Church", 76400)},
                { "Rotview Balcony", ("Rotview Balcony", 76401)},
                { "Fort Gael North", ("Fort Gael North", 76402)},
                { "Caelem Ruins", ("Caelem Ruins", 76403)},
                { "Cathedral of Dragon Communion", ("Cathedral of Dragon Communion", 76404)},
                { "Caelid Highway South", ("Caelid Highway South", 76405)},
                { "Smoldering Wall", ("Smoldering Wall", 76409)},
                { "Deep Siofra Well", ("Deep Siofra Well", 76410)},
                { "Southern Aeonia Swamp Bank", ("Southern Aeonia Swamp Bank", 76411)},
                { "Sellia Backstreets", ("Sellia Backstreets", 76414)},
                { "Chair-Crypt of Sellia", ("Chair-Crypt of Sellia", 76415)},
                { "Sellia Under-Stair", ("Sellia Under-Stair", 76416)},
                { "Impassable Greatbridge", ("Impassable Greatbridge", 76417)},
                { "Church of the Plague", ("Church of the Plague", 76418)},
                { "Redmane Castle Plaza", ("Redmane Castle Plaza", 76419)},
                { "Chamber Outside the Plaza", ("Chamber Outside the Plaza", 76420)},
                { "Starscourge Radahn", ("Starscourge Radahn", 76422)},
                { "Auriza Hero's Grave", ("Auriza Hero's Grave", 73010)},
                { "Auriza Side Tomb", ("Auriza Side Tomb", 73013)},
                { "Divine Tower of West Altus", ("Divine Tower of West Altus", 73430)},
                { "Sealed Tunnel", ("Sealed Tunnel", 73431)},
                { "Divine Tower of West Altus: Gate", ("Divine Tower of West Altus: Gate", 73432)},
                { "Outer Wall Phantom Tree", ("Outer Wall Phantom Tree", 76309)},
                { "Minor Erdtree Church", ("Minor Erdtree Church", 76310)},
                { "Hermit Merchant's Shack", ("Hermit Merchant's Shack", 76311)},
                { "Outer Wall Battleground", ("Outer Wall Battleground", 76312)},
                { "Capital Rampart", ("Capital Rampart", 76314)},
                { "Consecrated Snowfield Catacombs", ("Consecrated Snowfield Catacombs", 73019)},
                { "Cave of the Forlorn", ("Cave of the Forlorn", 73112)},
                { "Yelough Anix Tunnel", ("Yelough Anix Tunnel", 73211)},
                { "Consecrated Snowfield", ("Consecrated Snowfield", 76550)},
                { "Inner Consecrated Snowfield", ("Inner Consecrated Snowfield", 76551)},
                { "Ordina, Liturgical Town", ("Ordina, Liturgical Town", 76652)},
                { "Apostate Derelict", ("Apostate Derelict", 76653)},
                { "Maliketh, the Black Blade", ("Maliketh, the Black Blade", 71300)},
                { "Dragonlord Placidusax", ("Dragonlord Placidusax", 71301)},
                { "Dragon Temple Altar", ("Dragon Temple Altar", 71302)},
                { "Crumbling Beast Grave", ("Crumbling Beast Grave", 71303)},
                { "Crumbling Beast Grave Depths", ("Crumbling Beast Grave Depths", 71304)},
                { "Tempest-Facing Balcony", ("Tempest-Facing Balcony", 71305)},
                { "Dragon Temple", ("Dragon Temple", 71306)},
                { "Dragon Temple Transept", ("Dragon Temple Transept", 71307)},
                { "Dragon Temple Lift", ("Dragon Temple Lift", 71308)},
                { "Dragon Temple Rooftop", ("Dragon Temple Rooftop", 71309)},
                { "Beside the Great Bridge", ("Beside the Great Bridge", 71310)},
                { "Prince of Death's Throne", ("Prince of Death's Throne", 71230)},
                { "Root-Facing Cliffs", ("Root-Facing Cliffs", 71231)},
                { "Great Waterfall Crest", ("Great Waterfall Crest", 71232)},
                { "Deeproot Depths", ("Deeproot Depths", 71233)},
                { "The Nameless Eternal City", ("The Nameless Eternal City", 71234)},
                { "Across the Roots", ("Across the Roots", 71235)},
                { "Fractured Marika", ("Fractured Marika", 71900)},
                { "Malenia, Goddess of Rot", ("Malenia, Goddess of Rot", 71500)},
                { "Prayer Room", ("Prayer Room", 71501)},
                { "Elphael Inner Wall", ("Elphael Inner Wall", 71502)},
                { "Drainage Channel", ("Drainage Channel", 71503)},
                { "Haligtree Roots", ("Haligtree Roots", 71504)},
                { "Giant-Conquering Hero's Grave", ("Giant-Conquering Hero's Grave", 73017)},
                { "Giants' Mountaintop Catacombs", ("Giants' Mountaintop Catacombs", 73018)},
                { "Giants' Gravepost", ("Giants' Gravepost", 76506)},
                { "Church of Repose", ("Church of Repose", 76507)},
                { "Foot of the Forge", ("Foot of the Forge", 76508)},
                { "Fire Giant", ("Fire Giant", 76509)},
                { "Forge of the Giants", ("Forge of the Giants", 76510)},
                { "Hidden Path to the Haligtree", ("Hidden Path to the Haligtree", 73020)},
                { "Divine Tower of East Altus: Gate", ("Divine Tower of East Altus: Gate", 73450)},
                { "Divine Tower of East Altus", ("Divine Tower of East Altus", 73451)},
                { "Forbidden Lands", ("Forbidden Lands", 76500)},
                { "Grand Lift of Rold", ("Grand Lift of Rold", 76502)},
                { "Dragonbarrow Cave", ("Dragonbarrow Cave", 73110)},
                { "Sellia Hideaway", ("Sellia Hideaway", 73111)},
                { "Divine Tower of Caelid", ("Divine Tower of Caelid", 73440)},
                { "Divine Tower of Caelid: Center", ("Divine Tower of Caelid: Center", 73441)},
                { "Isolated Divine Tower", ("Isolated Divine Tower", 73460)},
                { "Dragonbarrow West", ("Dragonbarrow West", 76450)},
                { "Isolated Merchant's Shack (Greyoll's Dragonbarrow)", ("Isolated Merchant's Shack (Greyoll's Dragonbarrow)", 76451)},
                { "Dragonbarrow Fork", ("Dragonbarrow Fork", 76452)},
                { "Fort Faroth", ("Fort Faroth", 76453)},
                { "Bestial Sanctum", ("Bestial Sanctum", 76454)},
                { "Lenne's Rise", ("Lenne's Rise", 76455)},
                { "Farum Greatbridge", ("Farum Greatbridge", 76456)},
                { "Lake of Rot Shoreside", ("Lake of Rot Shoreside", 71216)},
                { "Grand Cloister", ("Grand Cloister", 71218)},
                { "Elden Throne (Leyndell, Ashen Capital)", ("Elden Throne (Leyndell, Ashen Capital)", 71120)},
                { "Erdtree Sanctuary (Leyndell, Ashen Capital)", ("Erdtree Sanctuary (Leyndell, Ashen Capital)", 71121)},
                { "East Capital Rampart (Leyndell, Ashen Capital)", ("East Capital Rampart (Leyndell, Ashen Capital)", 71122)},
                { "Leyndell, Capital of Ash", ("Leyndell, Capital of Ash", 71123)},
                { "Queen's Bedchamber (Leyndell, Ashen Capital)", ("Queen's Bedchamber (Leyndell, Ashen Capital)", 71124)},
                { "Divine Bridge (Leyndell, Ashen Capital)", ("Divine Bridge (Leyndell, Ashen Capital)", 71125)},
                { "Elden Throne (Leyndell, Royal Capital)", ("Elden Throne (Leyndell, Royal Capital)", 71100)},
                { "Erdtree Sanctuary (Leyndell, Royal Capital)", ("Erdtree Sanctuary (Leyndell, Royal Capital)", 71101)},
                { "East Capital Rampart (Leyndell, Royal Capital)", ("East Capital Rampart (Leyndell, Royal Capital)", 71102)},
                { "Lower Capital Church", ("Lower Capital Church", 71103)},
                { "Avenue Balcony", ("Avenue Balcony", 71104)},
                { "West Capital Rampart", ("West Capital Rampart", 71105)},
                { "Queen's Bedchamber (Leyndell, Royal Capital)", ("Queen's Bedchamber (Leyndell, Royal Capital)", 71107)},
                { "Fortified Manor, First Floor", ("Fortified Manor, First Floor", 71108)},
                { "Divine Bridge (Leyndell, Royal Capital)", ("Divine Bridge (Leyndell, Royal Capital)", 71109)},
                { "Stormfoot Catacombs", ("Stormfoot Catacombs", 73002)},
                { "Murkwater Catacombs", ("Murkwater Catacombs", 73004)},
                { "Murkwater Cave", ("Murkwater Cave", 73100)},
                { "Groveside Cave", ("Groveside Cave", 73103)},
                { "Coastal Cave", ("Coastal Cave", 73115)},
                { "Highroad Cave", ("Highroad Cave", 73117)},
                { "Limgrave Tunnels", ("Limgrave Tunnels", 73201)},
                { "Church of Elleh", ("Church of Elleh", 76100)},
                { "The First Step", ("The First Step", 76101)},
                { "Artist's Shack (Limgrave)", ("Artist's Shack (Limgrave)", 76103)},
                { "Third Church of Marika", ("Third Church of Marika", 76104)},
                { "Fort Haight West", ("Fort Haight West", 76105)},
                { "Agheel Lake South", ("Agheel Lake South", 76106)},
                { "Agheel Lake North", ("Agheel Lake North", 76108)},
                { "Church of Dragon Communion", ("Church of Dragon Communion", 76110)},
                { "Gatefront", ("Gatefront", 76111)},
                { "Seaside Ruins", ("Seaside Ruins", 76113)},
                { "Mistwood Outskirts", ("Mistwood Outskirts", 76114)},
                { "Murkwater Coast", ("Murkwater Coast", 76116)},
                { "Summonwater Village Outskirts", ("Summonwater Village Outskirts", 76119)},
                { "Waypoint Ruins Cellar", ("Waypoint Ruins Cellar", 76120)},
                { "Road's End Catacombs", ("Road's End Catacombs", 73003)},
                { "Black Knife Catacombs", ("Black Knife Catacombs", 73005)},
                { "Cliffbottom Catacombs", ("Cliffbottom Catacombs", 73006)},
                { "Stillwater Cave", ("Stillwater Cave", 73104)},
                { "Lakeside Crystal Cave", ("Lakeside Crystal Cave", 73105)},
                { "Academy Crystal Cave", ("Academy Crystal Cave", 73106)},
                { "Raya Lucaria Crystal Tunnel", ("Raya Lucaria Crystal Tunnel", 73202)},
                { "Study Hall Entrance", ("Study Hall Entrance", 73420)},
                { "Liurnia Tower Bridge", ("Liurnia Tower Bridge", 73421)},
                { "Divine Tower of Liurnia", ("Divine Tower of Liurnia", 73422)},
                { "Lake-Facing Cliffs", ("Lake-Facing Cliffs", 76200)},
                { "Liurnia Lake Shore", ("Liurnia Lake Shore", 76201)},
                { "Laskyar Ruins", ("Laskyar Ruins", 76202)},
                { "Scenic Isle", ("Scenic Isle", 76203)},
                { "Academy Gate Town", ("Academy Gate Town", 76204)},
                { "South Raya Lucaria Gate", ("South Raya Lucaria Gate", 76205)},
                { "Main Academy Gate", ("Main Academy Gate", 76206)},
                { "Grand Lift of Dectus", ("Grand Lift of Dectus", 76209)},
                { "Foot of the Four Belfries", ("Foot of the Four Belfries", 76210)},
                { "Sorcerer's Isle", ("Sorcerer's Isle", 76211)},
                { "Northern Liurnia Lake Shore", ("Northern Liurnia Lake Shore", 76212)},
                { "Road to the Manor", ("Road to the Manor", 76213)},
                { "Main Caria Manor Gate", ("Main Caria Manor Gate", 76214)},
                { "Slumbering Wolf's Shack", ("Slumbering Wolf's Shack", 76215)},
                { "Boilprawn Shack", ("Boilprawn Shack", 76216)},
                { "Artist's Shack (Liurnia of the Lakes)", ("Artist's Shack (Liurnia of the Lakes)", 76217)},
                { "Revenger's Shack", ("Revenger's Shack", 76218)},
                { "Folly on the Lake", ("Folly on the Lake", 76219)},
                { "Village of the Albinaurics", ("Village of the Albinaurics", 76220)},
                { "Liurnia Highway North", ("Liurnia Highway North", 76221)},
                { "Gate Town Bridge", ("Gate Town Bridge", 76222)},
                { "Eastern Liurnia Lake Shore", ("Eastern Liurnia Lake Shore", 76223)},
                { "Church of Vows", ("Church of Vows", 76224)},
                { "Ruined Labyrinth", ("Ruined Labyrinth", 76225)},
                { "Mausoleum Compound", ("Mausoleum Compound", 76226)},
                { "The Four Belfries", ("The Four Belfries", 76227)},
                { "Ranni's Rise", ("Ranni's Rise", 76228)},
                { "Ravine-Veiled Village", ("Ravine-Veiled Village", 76229)},
                { "Manor Upper Level", ("Manor Upper Level", 76230)},
                { "Manor Lower Level", ("Manor Lower Level", 76231)},
                { "Royal Moongazing Grounds", ("Royal Moongazing Grounds", 76232)},
                { "Gate Town North", ("Gate Town North", 76233)},
                { "Eastern Tableland", ("Eastern Tableland", 76234)},
                { "The Ravine", ("The Ravine", 76235)},
                { "Fallen Ruins of the Lake", ("Fallen Ruins of the Lake", 76236)},
                { "Converted Tower", ("Converted Tower", 76237)},
                { "Behind Caria Manor", ("Behind Caria Manor", 76238)},
                { "Temple Quarter", ("Temple Quarter", 76241)},
                { "East Gate Bridge Trestle", ("East Gate Bridge Trestle", 76242)},
                { "Crystalline Woods", ("Crystalline Woods", 76243)},
                { "Liurnia Highway South", ("Liurnia Highway South", 76244)},
                { "Jarburg", ("Jarburg", 76245)},
                { "Ranni's Chamber", ("Ranni's Chamber", 76247)},
                { "Haligtree Promenade", ("Haligtree Promenade", 71505)},
                { "Haligtree Canopy", ("Haligtree Canopy", 71506)},
                { "Haligtree Town", ("Haligtree Town", 71507)},
                { "Haligtree Town Plaza", ("Haligtree Town Plaza", 71508)},
                { "Cocoon of the Empyrean", ("Cocoon of the Empyrean", 71250)},
                { "Palace Approach Ledge-Road", ("Palace Approach Ledge-Road", 71251)},
                { "Dynasty Mausoleum Entrance", ("Dynasty Mausoleum Entrance", 71252)},
                { "Dynasty Mausoleum Midpoint", ("Dynasty Mausoleum Midpoint", 71253)},
                { "Moonlight Altar", ("Moonlight Altar", 76250)},
                { "Cathedral of Manus Celes", ("Cathedral of Manus Celes", 76251)},
                { "Altar South", ("Altar South", 76252)},
                { "Spiritcaller's Cave", ("Spiritcaller's Cave", 73122)},
                { "Zamor Ruins", ("Zamor Ruins", 76501)},
                { "Ancient Snow Valley Ruins", ("Ancient Snow Valley Ruins", 76503)},
                { "Freezing Lake", ("Freezing Lake", 76504)},
                { "First Church of Marika", ("First Church of Marika", 76505)},
                { "Whiteridge Road", ("Whiteridge Road", 76520)},
                { "Snow Valley Ruins Overlook", ("Snow Valley Ruins Overlook", 76521)},
                { "Castle Sol Main Gate", ("Castle Sol Main Gate", 76522)},
                { "Church of the Eclipse", ("Church of the Eclipse", 76523)},
                { "Castle Sol Rooftop", ("Castle Sol Rooftop", 76524)},
                { "Wyndham Catacombs", ("Wyndham Catacombs", 73007)},
                { "Gelmir Hero's Grave", ("Gelmir Hero's Grave", 73009)},
                { "Seethewater Cave", ("Seethewater Cave", 73107)},
                { "Volcano Cave", ("Volcano Cave", 73109)},
                { "Bridge of Iniquity", ("Bridge of Iniquity", 76350)},
                { "First Mt. Gelmir Campsite", ("First Mt. Gelmir Campsite", 76351)},
                { "Ninth Mt. Gelmir Campsite", ("Ninth Mt. Gelmir Campsite", 76352)},
                { "Road of Iniquity", ("Road of Iniquity", 76353)},
                { "Seethewater River", ("Seethewater River", 76354)},
                { "Seethewater Terminus", ("Seethewater Terminus", 76355)},
                { "Craftsman's Shack", ("Craftsman's Shack", 76356)},
                { "Primeval Sorcerer Azur", ("Primeval Sorcerer Azur", 76357)},
                { "Great Waterfall Basin", ("Great Waterfall Basin", 71220)},
                { "Mimic Tear", ("Mimic Tear", 71221)},
                { "Ancestral Woods", ("Ancestral Woods", 71224)},
                { "Aqueduct-Facing Cliffs", ("Aqueduct-Facing Cliffs", 71225)},
                { "Night's Sacred Ground", ("Night's Sacred Ground", 71226)},
                { "Nokron, Eternal City", ("Nokron, Eternal City", 71271)},
                { "Table of Lost Grace", ("Table of Lost Grace", 71190)},
                { "Magma Wyrm", ("Magma Wyrm", 73900)},
                { "Ruin-Strewn Precipice", ("Ruin-Strewn Precipice", 73901)},
                { "Ruin-Strewn Precipice Overlook", ("Ruin-Strewn Precipice Overlook", 73902)},
                { "Siofra River Bank", ("Siofra River Bank", 71222)},
                { "Worshippers' Woods", ("Worshippers' Woods", 71223)},
                { "Below the Well", ("Below the Well", 71227)},
                { "Siofra River Well Depths", ("Siofra River Well Depths", 71270)},
                { "Deathtouched Catacombs", ("Deathtouched Catacombs", 73011)},
                { "Limgrave Tower Bridge", ("Limgrave Tower Bridge", 73410)},
                { "Divine Tower of Limgrave", ("Divine Tower of Limgrave", 73412)},
                { "Stormhill Shack", ("Stormhill Shack", 76102)},
                { "Saintsbridge", ("Saintsbridge", 76117)},
                { "Warmaster's Shack", ("Warmaster's Shack", 76118)},
                { "Godrick the Grafted", ("Godrick the Grafted", 71000)},
                { "Margit, the Fell Omen", ("Margit, the Fell Omen", 71001)},
                { "Castleward Tunnel", ("Castleward Tunnel", 71002)},
                { "Gateside Chamber", ("Gateside Chamber", 71003)},
                { "Stormveil Cliffside", ("Stormveil Cliffside", 71004)},
                { "Rampart Tower", ("Rampart Tower", 71005)},
                { "Liftside Chamber", ("Liftside Chamber", 71006)},
                { "Secluded Cell", ("Secluded Cell", 71007)},
                { "Stormveil Main Gate", ("Stormveil Main Gate", 71008)},
                { "Cave of Knowledge", ("Cave of Knowledge", 71800)},
                { "Stranded Graveyard", ("Stranded Graveyard", 71801)},
                { "Cathedral of the Forsaken", ("Cathedral of the Forsaken", 73500)},
                { "Underground Roadside", ("Underground Roadside", 73501)},
                { "Forsaken Depths", ("Forsaken Depths", 73502)},
                { "Leyndell Catacombs", ("Leyndell Catacombs", 73503)},
                { "Frenzied Flame Proscription", ("Frenzied Flame Proscription", 73504)},
                { "Aeonia Swamp Shore", ("Aeonia Swamp Shore", 76406)},
                { "Astray from Caelid Highway North", ("Astray from Caelid Highway North", 76407)},
                { "Heart of Aeonia", ("Heart of Aeonia", 76412)},
                { "Inner Aeonia", ("Inner Aeonia", 76413)},
                { "Rykard, Lord of Blasphemy", ("Rykard, Lord of Blasphemy", 71600)},
                { "Temple of Eiglay", ("Temple of Eiglay", 71601)},
                { "Volcano Manor", ("Volcano Manor", 71602)},
                { "Prison Town Church", ("Prison Town Church", 71603)},
                { "Guest Hall", ("Guest Hall", 71604)},
                { "Audience Pathway", ("Audience Pathway", 71605)},
                { "Abductor Virgin", ("Abductor Virgin", 71606)},
                { "Subterranean Inquisition Chamber", ("Subterranean Inquisition Chamber", 71607)},
                { "Tombsward Catacombs", ("Tombsward Catacombs", 73000)},
                { "Impaler's Catacombs", ("Impaler's Catacombs", 73001)},
                { "Earthbore Cave", ("Earthbore Cave", 73101)},
                { "Tombsward Cave", ("Tombsward Cave", 73102)},
                { "Morne Tunnel", ("Morne Tunnel", 73200)},
                { "Church of Pilgrimage", ("Church of Pilgrimage", 76150)},
                { "Castle Morne Rampart", ("Castle Morne Rampart", 76151)},
                { "Tombsward", ("Tombsward", 76152)},
                { "South of the Lookout Tower", ("South of the Lookout Tower", 76153)},
                { "Ailing Village Outskirts", ("Ailing Village Outskirts", 76154)},
                { "Beside the Crater-Pocked Glade", ("Beside the Crater-Pocked Glade", 76155)},
                { "Isolated Merchant's Shack (Weeping Peninsula)", ("Isolated Merchant's Shack (Weeping Peninsula)", 76156)},
                { "Bridge of Sacrifice", ("Bridge of Sacrifice", 76157)},
                { "Castle Morne Lift", ("Castle Morne Lift", 76158)},
                { "Behind the Castle", ("Behind the Castle", 76159)},
                { "Beside the Rampart Gaol", ("Beside the Rampart Gaol", 76160)},
                { "Morne Moangrave", ("Morne Moangrave", 76161)},
                { "Fourth Church of Marika", ("Fourth Church of Marika", 76162)},
                #region DLC Graces
                { "Theatre of the Divine Beast", ("Theatre of the Divine Beast", 72000)},
                { "Belurat, Tower Settlement", ("Belurat, Tower Settlement", 72001)},
                { "Small Private Altar", ("Small Private Altar", 72002)},
                { "Stagefront", ("Stagefront", 72003)},
                { "Gate of Divinity", ("Gate of Divinity", 72010)},
                { "Enir-Ilim: Outer Wall", ("Enir-Ilim: Outer Wall", 72012)},
                { "First Rise", ("First Rise", 72013)},
                { "Spiral Rise", ("Spiral Rise", 72014)},
                { "Cleansing Chamber Anteroom", ("Cleansing Chamber Anteroom", 72015)},
                { "Divine Gate Front Staircase", ("Divine Gate Front Staircase", 72016)},
                { "Main Gate Plaza", ("Main Gate Plaza", 72101)},
                { "Shadow Keep Main Gate", ("Shadow Keep Main Gate", 72102)},
                { "Church District Entrance", ("Church District Entrance", 72106)},
                { "Sunken Chapel", ("Sunken Chapel", 72107)},
                { "Tree,Worship Passage", ("Tree,Worship Passage", 72108)},
                { "Tree,Worship Sanctum", ("Tree,Worship Sanctum", 72109)},
                { "Messmer's Dark Chamber", ("Messmer's Dark Chamber", 72110)},
                { "Storehouse, First Floor", ("Storehouse, First Floor", 72111)},
                { "Storehouse, Fourth Floor", ("Storehouse, Fourth Floor", 72112)},
                { "Storehouse, Seventh Floor", ("Storehouse, Seventh Floor", 72113)},
                { "Dark Chamber Entrance", ("Dark Chamber Entrance", 72114)},
                { "Storehouse, Back Section", ("Storehouse, Back Section", 72116)},
                { "Storehouse, Loft", ("Storehouse, Loft", 72117)},
                { "West Rampart", ("West Rampart", 72120)},
                { "Garden of Deep Purple", ("Garden of Deep Purple", 72200)},
                { "Stone Coffin Fissure", ("Stone Coffin Fissure", 72201)},
                { "Fissure Cross", ("Fissure Cross", 72202)},
                { "Fissure Waypoint", ("Fissure Waypoint", 72203)},
                { "Fissure Depths", ("Fissure Depths", 72204)},
                { "Finger Birthing Grounds", ("Finger Birthing Grounds", 72500)},
                { "Discussion Chamber", ("Discussion Chamber", 72800)},
                { "Manse Hall", ("Manse Hall", 72801)},
                { "Midra's Library", ("Midra's Library", 72802)},
                { "Second Floor Chamber", ("Second Floor Chamber", 72803)},
                { "Fog Rift Catacombs", ("Fog Rift Catacombs", 74000)},
                { "Ruined Forge Lava Intake", ("Ruined Forge Lava Intake", 74200)},
                { "Rivermouth Cave", ("Rivermouth Cave", 74300)},
                { "Dragon's Pit", ("Dragon's Pit", 74301)},
                { "Dragon's Pit Terminus", ("Dragon's Pit Terminus", 74351)},
                { "Cliffroad Terminus", ("Cliffroad Terminus", 76804)},
                { "Main Gate Cross", ("Main Gate Cross", 76803)},
                { "Gravesite Plain", ("Gravesite Plain", 76800)},
                { "Three,Path Cross", ("Three,Path Cross", 76802)},
                { "Greatbridge, North", ("Greatbridge, North", 76805)},
                { "Scorched Ruins", ("Scorched Ruins", 76801)},
                { "Ellac River Cave", ("Ellac River Cave", 76812)},
                { "Castle Front", ("Castle Front", 76813)},
                { "Pillar Path Waypoint", ("Pillar Path Waypoint", 76811)},
                { "Pillar Path Cross", ("Pillar Path Cross", 76810)},
                { "Belurat Gaol", ("Belurat Gaol", 74100)},
                { "Ellac River Downstream", ("Ellac River Downstream", 76830)},
                { "Charo's Hidden Grave", ("Charo's Hidden Grave", 76841)},
                { "Lamenter's Gaol", ("Lamenter's Gaol", 74102)},
                { "Castle Ensis Checkpoint", ("Castle Ensis Checkpoint", 76821)},
                { "Ensis Moongazing Grounds", ("Ensis Moongazing Grounds", 76823)},
                { "Castle,Lord's Chamber", ("Castle,Lord's Chamber", 76822)},
                { "Cerulean Coast West", ("Cerulean Coast West", 76832)},
                { "The Fissure", ("The Fissure", 76833)},
                { "Cerulean Coast Cross", ("Cerulean Coast Cross", 76835)},
                { "Cerulean Coast", ("Cerulean Coast", 76831)},
                { "Finger Ruins of Rhia", ("Finger Ruins of Rhia", 76834)},
                { "Grand Altar of Dragon Communion", ("Grand Altar of Dragon Communion", 76840)},
                { "Divided Falls", ("Divided Falls", 76861)},
                { "Abyssal Woods", ("Abyssal Woods", 76860)},
                { "Forsaken Graveyard", ("Forsaken Graveyard", 76862)},
                { "Church Ruins", ("Church Ruins", 76864)},
                { "Woodland Trail", ("Woodland Trail", 76863)},
                { "Foot of the Jagged Peak", ("Foot of the Jagged Peak", 76850)},
                { "Jagged Peak Mountainside", ("Jagged Peak Mountainside", 76851)},
                { "Jagged Peak Summit", ("Jagged Peak Summit", 76852)},
                { "Rest of the Dread Dragon", ("Rest of the Dread Dragon", 76853)},
                { "Ancient Ruins, Grand Stairway", ("Ancient Ruins, Grand Stairway", 76944)},
                { "Church of the Bud", ("Church of the Bud", 76945)},
                { "Church of the Bud, Main Entrance", ("Church of the Bud, Main Entrance", 76943)},
                { "Rauh Ancient Ruins, West", ("Rauh Ancient Ruins, West", 76942)},
                { "Rauh Ancient Ruins, East", ("Rauh Ancient Ruins, East", 76941)},
                { "Viaduct Minor Tower", ("Viaduct Minor Tower", 76940)},
                { "Temple Town Ruins", ("Temple Town Ruins", 76913)},
                { "Ravine North", ("Ravine North", 76914)},
                { "Scorpion River Catacombs", ("Scorpion River Catacombs", 74001)},
                { "Taylew's Ruined Forge", ("Taylew's Ruined Forge", 74203)},
                { "Ancient Ruins Base", ("Ancient Ruins Base", 76912)},
                { "Darklight Catacombs", ("Darklight Catacombs", 74002)},
                { "Bonny Gaol", ("Bonny Gaol", 74101)},
                { "Highroad Cross", ("Highroad Cross", 76900)},
                { "Scadu Altus, West", ("Scadu Altus, West", 76907)},
                { "Moorth Highway, South", ("Moorth Highway, South", 76908)},
                { "Fort of Reprimand", ("Fort of Reprimand", 76909)},
                { "Behind the Fort of Reprimand", ("Behind the Fort of Reprimand", 76910)},
                { "Moorth Ruins", ("Moorth Ruins", 76902)},
                { "Bonny Village", ("Bonny Village", 76903)},
                { "Castle Watering Hole", ("Castle Watering Hole", 76916)},
                { "Ruined Forge of Starfall Past", ("Ruined Forge of Starfall Past", 74202)},
                { "Scaduview Cross", ("Scaduview Cross", 76911)},
                { "Recluses' River Downstream", ("Recluses' River Downstream", 76918)},
                { "Recluses' River Upstream", ("Recluses' River Upstream", 76917)},
                { "Bridge Leading to the Village", ("Bridge Leading to the Village", 76904)},
                { "Cathedral of Manus Metyr", ("Cathedral of Manus Metyr", 76906)},
                { "Church District Highroad", ("Church District Highroad", 76905)},
                { "Scaduview", ("Scaduview", 76930)},
                { "Shadow Keep, Back Gate", ("Shadow Keep, Back Gate", 76931)},
                { "Fingerstone Hill", ("Fingerstone Hill", 76936)},
                { "Hinterland Bridge", ("Hinterland Bridge", 76937)},
                { "Hinterland", ("Hinterland", 76935)},
                { "Scadutree Base", ("Scadutree Base", 76960)}
                #endregion
            };

            if (graceMapping.TryGetValue(grace, out var bossInfo))
            {
                return new GraceER { Title = bossInfo.Title, Id = bossInfo.Id };
            }
            else
            {
                throw new ArgumentException($"Invalid grace string: {grace}");
            }
        }

        #endregion
        #region Position.Elden
        [Serializable]
        public class PositionER
        {
            public SoulMemory.EldenRing.Position vector = new SoulMemory.EldenRing.Position();
            public bool IsSplited = false;
            public string Mode;
            public string Title;
        }
        #endregion
        #region CustomFlag.Elden
        public class CustomFlagER
        {
            public uint Id;
            public bool IsSplited = false;
            public string Mode;
            public string Title;
        }
        #endregion
    }

    [Serializable]
    public class DTElden
    {
        //var Settings
        public bool enableSplitting = false;
        public bool autoTimer = false;
        public bool gameTimer = false;
        public int positionMargin = 5;
        public bool ResetIGTNG = false;
        //Flags to Split
        public List<DefinitionsElden.BossER> bossToSplit = new List<DefinitionsElden.BossER>();
        public List<DefinitionsElden.GraceER> graceToSplit = new List<DefinitionsElden.GraceER>();
        public List<DefinitionsElden.PositionER> positionToSplit = new List<DefinitionsElden.PositionER>();
        public List<DefinitionsElden.CustomFlagER> flagsToSplit = new List<DefinitionsElden.CustomFlagER>();


        public List<DefinitionsElden.BossER> GetBossToSplit() => this.bossToSplit;

        public List<DefinitionsElden.GraceER> GetGraceToSplit() => this.graceToSplit;

        public List<DefinitionsElden.PositionER> GetPositionToSplit() => this.positionToSplit;

        public List<DefinitionsElden.CustomFlagER> GetFlagsToSplit() => this.flagsToSplit;
    }
}
